- name: Check Password Status
  shell: "getent shadow {{ item.name }} | cut -d':' -f2"
  register: user_password
  changed_when: false
  with_items: "{{ users }}"
  when: "{{userIsRelevent}}"

- name: Password Status Report
  debug:
    msg: "User {{ item.item.name }} has password set: {{ item.stdout != '!' }}"
  with_items: "{{ user_password.results }}"