- name: Ensure authorized keys for users
  hosts: remote
  gather_facts: no
  become: yes
  
  tasks:
  - name: Check to see if user exists
    group:
      name: "{{ item.machines[0].groups }}"
    with_items: "{{ users }}"

  - name: Ensure user exists
    user:
      name: "{{ item.name }}"
      groups: "{{ item.machines[0].groups }}"
      shell: "{{ item.machines[0].shell }}"
    with_items: "{{ users }}"

  - name: Print user details
    ansible.builtin.debug:
      msg: "Ensuring user exists: {{ item.name }} - Groups: {{ item.machines[0].groups }} - Shell: {{ item.machines[0].shell }}"
    with_items: "{{ users }}"